# Generated by Django 5.2.3 on 2025-07-22 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('country_code', models.CharField(blank=True, max_length=5, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'number')},
            },
        ),
        migrations.CreateModel(
            name='WhatsAppCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Campaign', max_length=255)),
                ('numbers', models.TextField(blank=True, null=True)),
                ('message1', models.TextField(blank=True, null=True)),
                ('message2', models.TextField(blank=True, null=True)),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='campaign_excels/')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='campaign_attachments/')),
                ('country_code', models.CharField(blank=True, max_length=10)),
                ('deduplicate', models.BooleanField(default=False)),
                ('whatsapp_group', models.CharField(blank=True, max_length=255)),
                ('messaging_mode', models.CharField(blank=True, max_length=100)),
                ('safe_mode', models.BooleanField(default=False)),
                ('unsafe_mode', models.BooleanField(default=False)),
                ('swipe_after', models.IntegerField(blank=True, null=True)),
                ('delay', models.IntegerField(blank=True, null=True)),
                ('schedule_time', models.DateTimeField(blank=True, null=True)),
                ('friendly_numbers', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bulk.whatsappaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'custom_campaign',
            },
        ),
    ]
