# Generated by Django 5.2.3 on 2025-07-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappcampaign',
            name='account',
        ),
        migrations.RemoveField(
            model_name='whatsappcampaign',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='whatsappcampaign',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='whatsappcampaign',
            name='is_sent',
        ),
        migrations.RemoveField(
            model_name='whatsappcampaign',
            name='messaging_mode',
        ),
        migrations.AlterField(
            model_name='whatsappcampaign',
            name='country_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='whatsappcampaign',
            name='delay',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='whatsappcampaign',
            name='excel_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='whatsappcampaign',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='whatsappcampaign',
            name='numbers',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='whatsappcampaign',
            name='swipe_after',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='whatsappcampaign',
            name='whatsapp_group',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='whatsappcampaign',
            table=None,
        ),
    ]
