# Generated by Django 5.2.3 on 2025-07-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk', '0002_remove_whatsappcampaign_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappcampaign',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
