# Generated by Django 5.2.3 on 2025-07-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk', '0003_whatsappcampaign_is_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappcampaign',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
