# Generated by Django 5.2.3 on 2025-07-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk', '0004_whatsappcampaign_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappaccount',
            name='session_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
