# Generated by Django 5.2.3 on 2025-07-29 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk', '0005_whatsappaccount_session_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappcampaign',
            name='whatsapp_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bulk.whatsappaccount'),
        ),
    ]
