# Generated by Django 5.2.3 on 2025-08-12 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulk', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
