# Generated by Django 5.2.3 on 2025-08-16 10:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk', '0008_delete_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whatsappaccount',
            options={'verbose_name': 'WhatsApp Account', 'verbose_name_plural': 'WhatsApp Accounts'},
        ),
        migrations.AddField(
            model_name='whatsappaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whatsappaccount',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatsappaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='whatsappaccount',
            name='country_code',
            field=models.CharField(default='91', max_length=5),
        ),
        migrations.AlterField(
            model_name='whatsappaccount',
            name='number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappaccount',
            name='session_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
