# Generated by Django 5.2.3 on 2025-08-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk', '0009_alter_whatsappaccount_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whatsappaccount',
            options={},
        ),
        migrations.RemoveField(
            model_name='whatsappaccount',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='whatsappaccount',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='whatsappaccount',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='whatsappaccount',
            name='country_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappaccount',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappaccount',
            name='session_path',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
