# Generated by Django 5.2.3 on 2025-08-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk', '0010_alter_whatsappaccount_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappaccount',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
