# Generated by Django 5.2.3 on 2025-08-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk', '0011_whatsappaccount_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappaccount',
            name='driver_pid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
