# Generated by Django 5.2.3 on 2026-08-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk', '0012_whatsappaccount_driver_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappaccount',
            name='driver_pid',
        ),
        migrations.AddField(
            model_name='whatsappcampaign',
            name='send_as_caption',
            field=models.BooleanField(default=True),
        ),
    ]
