# Generated by Django 5.2.3 on 2026-07-24 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulk', '0012_whatsappaccount_driver_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappaccount',
            name='driver_pid',
        ),
    ]
