# Generated by Django 5.2.3 on 2026-08-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk', '0013_remove_whatsappaccount_driver_pid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappcampaign',
            name='use_ai_spintax',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatsappcampaign',
            name='use_normal_spintax',
            field=models.BooleanField(default=False),
        ),
    ]
