# Generated by Django 5.2.3 on 2026-08-06 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk', '0014_whatsappcampaign_use_ai_spintax_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendlyNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendly_numbers', to='bulk.whatsappaccount')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('account', 'number'), name='unique_friendly_number_per_account')],
            },
        ),
    ]
