# Generated by Django 5.2.3 on 2026-08-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk', '0015_friendlynumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
