# Generated by Django 5.2.3 on 2026-08-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk', '0016_appsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappcampaign',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappcampaign',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='whatsappcampaign',
            name='total_failed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='whatsappcampaign',
            name='total_messages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='whatsappcampaign',
            name='total_sent',
            field=models.IntegerField(default=0),
        ),
    ]
