# Generated by Django 5.2.3 on 2026-08-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk', '0017_whatsappcampaign_created_at_whatsappcampaign_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappcampaign',
            name='detailed_report',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
