# Generated by Django 5.2.3 on 2026-08-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk', '0018_whatsappcampaign_detailed_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappcampaign',
            name='batch_break_interval',
            field=models.IntegerField(default=20),
        ),
    ]
