# Generated by Django 5.2.3 on 2026-08-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk', '0019_whatsappcampaign_batch_break_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappcampaign',
            name='break_duration',
            field=models.IntegerField(default=3),
        ),
    ]
