# Generated by Django 5.2.3 on 2026-08-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk', '0020_whatsappcampaign_break_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappcampaign',
            name='batch_break_interval',
            field=models.IntegerField(default=15),
        ),
    ]
