"""
Django settings for whatsapp project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
if getattr(sys, 'frozen', False):
    BASE_DIR = Path(sys._MEIPASS)
else:
    BASE_DIR = Path(__file__).resolve().parent.parent

WHATSAPP_SESSIONS_DIR = os.path.join(BASE_DIR, "whatsapp_sessions")

os.makedirs(WHATSAPP_SESSIONS_DIR, exist_ok=True)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-c3np$3n6knzv2h##8m+(yofbj)x!et#^v%ul$bdt2ax^46!h56'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bulk',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'whatsapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'bulk', 'templates'),
            os.path.join(BASE_DIR, 'templates'),
            os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'bulk', 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'bulk.context_processors.account_list',
            ],
        },
    },
]

WSGI_APPLICATION = 'whatsapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Create a permanent hidden folder for the app data
APPDATA_DIR = os.path.join(os.environ.get('APPDATA', str(BASE_DIR)), 'WhatsApp Commune')
os.makedirs(APPDATA_DIR, exist_ok=True)

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        # Save the database in APPDATA so it survives app restarts
        'NAME': os.path.join(APPDATA_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = []


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
LOGIN_URL = '/login/'  # Or wherever your login page is

# Save user uploads (attachments) in APPDATA so they don't get deleted
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(APPDATA_DIR, 'media')
os.makedirs(MEDIA_ROOT, exist_ok=True)

LOGIN_REDIRECT_URL = '/add-account/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Guarantee users stay logged in for 10 years (Desktop App Behavior)
SESSION_COOKIE_AGE = 315360000 
SESSION_EXPIRE_AT_BROWSER_CLOSE = False


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

import os
from dotenv import load_dotenv
load_dotenv()

# Gemini AI API Configuration
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")

# Fallback sequence for models. Falls back automatically if one model hits Rate Limit (429) or is Unavailable (503).
GEMINI_MODELS = [
    os.environ.get("GEMINI_PRIMARY_MODEL", "gemini-3.5-flash-lite"),
    "gemini-3.7-flash",
    "gemini-3.6-flash",
    "gemini-3.1-flash-lite"
]
